#sdk: "/home/prabhat/.rvm/gems/ruby-1.8.7-p352/gems/rhodes-3.2.3"
sdkversion: 3.2.1
name: employee_application
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.employeeapplication
  BundleURLScheme: employeeapplication
wp:
  productid: '705c89b0-2496-012f-b78b-782bcbb1b5f7'
symbian:
  uid: '0xe4a292d8'
android:
  version: 2.1

extensions: ["json", "another-extension"]
